# -*- coding: utf-8 -*-

def get_historical_metadata_altruns(model):
    
    """Subfunction of <analysis_hist_<date>.py>; Python function assigning metadata to the coupled model configurations contributing historical experiments to CMIP5 and 6
    Dependencies: numpy
    input = name of the coupled model configuration (list of character strings), possible entries are (case-sensitive!):
    ['access10','access13','access_cm2','access_esm1_5','awi_esm_1_1_lr','bcc_csm1_1','bcc_csm2_mr','ccsm4','cmcc_cm','cmcc_cm2_hr4','cmcc_cm2_sr5','cmcc_esm2','canesm2','canesm5',
    'cnrm_cm5','cnrm_cm6_1','cnrm_cm6_1_hr','cnrm_esm2_1','csiro_mk3_6_0','ec_earth','ec_earth3','ec_earth3_veg','ec_earth3_veg_lr','ec_earth3_aerchem',
    'ec_earth3_cc','fgoals_g2','fgoals_g3','gfdl_cm3','gfdl_cm4','gfdl_esm2g','gfdl_esm4','giss_e2_h','giss_e2_r','giss_e2_1_g','hadgem2_es','hadgem2_cc',
    'hadgem3_gc31_mm','iitm_esm','inm_cm4','inm_cm5','ipsl_cm5a_lr','ipsl_cm5a_mr','ipsl_cm6a_lr','kiost_esm','miroc5','miroc6','miroc_esm','miroc_es2l','mpi_esm_lr',
    'mpi_esm_mr','mpi_esm_1_2_lr','mpi_esm_1_2_hr','mpi_esm_1_2_ham','mri_esm1','mri_esm2_0','nesm3','noresm1_m','noresm2_lm','noresm2_mm','sam0_unicon','taiesm1']
    output = mrun_f (string) are the run specification, family_f (string) either gcm or esm, doi_f (string) points to reference article(s),
    atmos_f (string) to the AGCM, surface_f (string) to the land surface model, ocean_f (string) to the OGCM, seaice_f (string) to the sea-ice model,
    aersol_f (string) to the aerosol model, chemistry_f (string) to the atmospheric chemistry model(s) in the troposphere and stratosphere,
    obgc_f (string) to the ocean biogeochemistry model, landice_f (string) to the ice-sheet model, coupler_f (string) to the coupling software,
    complex_f is the complexity code described DOI: 10.5194/gmd-2020-418, add_info (string) adds additional info about the component models,
    cmip_f(int) is the cmip generation, rgb_f(string) is the rgb code for the model, marker_f(string) is a specific marker used for visualization,
    latres_atm_f (int) is the number of latitudinal grid-boxes in the AGCM obtained from the reference article and/or netCDF files from ESGF,
    lonres_atm_f (int) is the number of longitudinal grid-boxes in the AGCM, lev_atm_f (int) the number of vertical layers in the AGCM,
    latres_oc_f (int) is the number of latitudinal grid-boxes in the AGCM, lonres_oc_f (int) is the number of longitudinal grid-boxes in the OGCM,
    lev_oc_f (int) is the number of vertical layers in the OGCM, ecs_f (int) and tcr_f (int) are the equilibrium climate sensitivity and transient climate response
    obtained from DOI: 10.1126/sciadv.aba198; if the information for a corresponding parameter could not be found or is not yet in use, then it is set to np.nan.
    Definitions and additional information:
    complex_f integers are for 1. Atmosphere, 2. Land-surface, 3. Ocean, 4. Sea-ice, 5. Vegetation properties, 6. Terrestrial biogeochemistry (tbgc),
    7. Aerosols, 8. Atmospheric chemistry, 9. Ocean biogeochemistry (obgc), 10. Ice sheet dynamics;
    0 = absent, 1 = prescribed or non-interactive or semi-offline (in case of IPSL-CM5A or MPI-ESM1.2-HAM), 2 = interactive and interacting with at least 1 other climate system component
    If the metadata in the nc files (source_id argument) does not agree with the description in the reference article(s), preference is given to the article information.
    If the complexity code was confirmed by a model developer, this is indicated by a comment after the code
    @Author: Swen Brands, MeteoGalicia - Xunta de Galicia, swen.brands@gmail.com
    @Contributors: Jesús Fernández (UC, Spain), Jian Cao (NUIST, China), Bin Wang (IPRC, Hawaii), Laurent Li (LMD, France), Tongwen Wu (Beijing Climate Center, China),
    Evgeny Volodin (INM, Russia), Hiroaki Tatebe (JAMSTEC, Japan), Swapna Panickal (IITM, India), YoungHo Kim (Pukyong National University, Korea),
    Thorsten Mauritsen (MPI, Germany), Øyvind Seland (Norwegian Meteorological Institute), Seiji Yukimoto (MRI, Japan), Klaus Wyser and Ralf Döscher (SMHI, Sweden),
    Annalisa Cherchie and Enrico Scoccimarro (CMCC, Italy), Aurore Voldoire and Roland Séférian (CNRM, France), Olivier Boucher (IPSL,France),
    Peter Gent (NCAR, USA), Tido Semmler (AWI, Germany), Gill Martin (Met Office, UK), Ina Tegen (TROPOS, Germany) and Huan Guo (NOAA, USA)
    """

    global mrun_f, complex_f, family_f, cmip_f, rgb_f, marker_f, latres_atm_f, lonres_atm_f, lev_atm_f, latres_oc_f, lonres_oc_f, lev_oc_f, ecs_f, tcr_f
    if model == 'access10':
        fullname_f = 'ACCESS1-0 2011'
        mrun_f = 'r1i1p1'
        family_f = 'gcm'
        doi_f = '10.22499/2.6301.006, 10.22499/2.6301.004'
        atmos_f = 'ACCESS1.0 uses the HadGEM2(r1.1) atmospheric physics (Martin et al. 2011, Collins et al. 2011) including the Smith (1990) cloud scheme' #the AGCM's source attribute is identical to ACCESS-1.3. However,  the ref. article states the AGMs are different! Preference is given to the article.
        surface_f = 'MOSES2 (1.875 degree EW x 1.25 degree NS, 4 levels), carbon fluxes have not been included in the ACCESS CMIP5 submissions'
        ocean_f = 'NOAA/GFDL MOM4p1 (nominal 1.0 degree EW x 1.0 degrees NS, tripolar north of 65N, equatorial refinement to 1/3 degree from 10S to 10 N, cosine dependent NS south of 25S, 50 levels)'
        seaice_f = 'CICE4.1 (nominal 1.0 degree EW x 1.0 degrees NS, tripolar north of 65N, equatorial refinement to 1/3 degree from 10S to 10 N, cosine dependent NS south of 25S)'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3.25'
        complex_f = '2222002000' #provided by Dave Bi, Tilo Ziehn and Matt Woodhouse
        addinfo_f = 'this is the basic ACCESS model version with atmospheric physics from HadGEM2(r1.1). Note that while MOSES and CABLE are both able to calculate carbon fluxes, these have not been assessed or submitted for the ACCESS1.0 and ACCESS1.3 simulations.'
        cmip_f = 5
        rgb_f = 'blue' #blue
        marker_f = 'X'
        latres_atm_f = 144
        lonres_atm_f = 192
        lev_atm_f = 38
        latres_oc_f = 300 #from reference article
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = 3.8 #following Meehl et al. 2020 Sciences Advances, doi: 10.1126/sciadv.aba1981
        tcr_f = 1.9
    elif model == 'access13':
        fullname_f = 'ACCESS1.3 2011'
        mrun_f = 'r1i1p1'
        family_f = 'gcm'
        doi_f = '10.22499/2.6301.006, 10.22499/2.6301.004, 10.1071/ES19040, 10.22499/2.6301.005'
        atmos_f = 'ACCESS1.3 uses atmospheric physics similar to that of the Met Office GA1.0 model configuration (Hewitt et al. 2011), including the PC2 cloud scheme (Wilson et al. 2008)' #the source attribute is wrong for this model version although the reference article underlines the AGMs are different!
        surface_f = 'CABLE1.8 (1.875 degree EW x 1.25 degree NS, 6 levels, carbon fluxes have not been included in the ACCESS CMIP5 submissions' #the source attribute (stating CALBE1.0) is in conflict with 10.1071/ES19040 (stating CALBE1.8 on page D)
        ocean_f = 'NOAA/GFDL MOM4p1 (nominal 1.0 degree EW x 1.0 degrees NS, tripolar north of 65N, equatorial refinement to 1/3 degree from 10S to 10 N, cosine dependent NS south of 25S, 50 levels)'
        seaice_f = 'CICE4.1 (nominal 1.0 degree EW x 1.0 degrees NS, tripolar north of 65N, equatorial refinement to 1/3 degree from 10S to 10 N, cosine dependent NS south of 25S)'
        aerosols_f = 'CLASSIC'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3.25'
        complex_f = '2222002000' #provided by Dave Bi, Tilo Ziehn and Matt Woodhouse
        addinfo_f = 'This was the aspirational ACCESS model version used in CMIP5. It was a key step on the way to attaining a full earth system model as laid out in the original ACCESS project plan. Note that while MOSES and CABLE are both able to calculate carbon fluxes, these have not been assessed or submitted for the ACCESS1.0 and ACCESS1.3 simulations.'
        cmip_f = 5
        rgb_f = 'blue'
        marker_f = 'P'
        latres_atm_f = 144
        lonres_atm_f = 192
        lev_atm_f = 38
        latres_oc_f = 300 #from reference article
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = 3.5
        tcr_ = 1.6
    elif model == 'access_cm2':
        fullname_f = 'ACCESS-CM2 (2019)'
        mrun_f = 'r1i1p1f1'
        family_f = 'gcm'
        doi_f = '10.1071/ES19040'
        atmos_f = 'MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)'
        surface_f = 'CABLE2.5'
        ocean_f = 'ACCESS-OM2 (GFDL-MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)'
        seaice_f = 'CICE5.1.2 (same grid as ocean)'
        aerosols_f = 'UKCA-GLOMAP-mode'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'CERFACS OASIS3-MCT'
        complex_f = '2222002000' #provided by Dave Bi, Tilo Ziehn and Matt Woodhouse
        addinfo_f = 'Includes a non-interactive ice-sheet representation. It should be noted that ACCESS-CM2 continues to utilise JULES representations for some terrestrial processes, particularly dust source/deposition and river routing'
        cmip_f = 6
        rgb_f = 'blue'
        marker_f = 'v'
        latres_atm_f = 144
        lonres_atm_f = 192
        lev_atm_f = 85
        latres_oc_f = 300 #from in metadata in file!
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = 4.7
        tcr_f = 2.1
    elif model == 'access_esm1_5':
        fullname_f = 'ACCESS-ESM1.5 (2019)'
        mrun_f = 'r3i1p1f1'
        family_f = 'esm'
        doi_f = '10.1071/ES19035, see Fig. 1 therein for an overview of all ACCESS models'
        atmos_f = 'HadGAM2 (r1.1, N96; 192 x 145 longitude/latitude; 38 levels; top level 39255 m)'
        surface_f = 'CABLE2.4'
        ocean_f = 'ACCESS-OM2 (MOM5, tripolar primarily 1deg; 360 x 300 longitude/latitude; 50 levels; top grid cell 0-10 m)'
        seaice_f = 'CICE5.1.2 (same grid as ocean)'
        aerosols_f = 'CLASSIC (v1.0)'
        chemistry_f = 'none'
        obgc_f = ' WOMBAT (same grid as ocean)'
        landice_f = 'none'
        coupler_f = 'OASIS-MCT'
        complex_f = '2222122020' #provided by Dave Bi, Tilo Ziehn and Matt Woodhouse
        addinfo_f = 'It should be noted that ACCESS-CM2 continues to utilise JULES representations for some terrestrial processes, particularly dust source/deposition and river routing'
        cmip_f = 6
        rgb_f = 'blue'
        marker_f = '<'
        latres_atm_f = 145 #from in metadata in file!
        lonres_atm_f = 192
        lev_atm_f = 38
        latres_oc_f = 300
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = 3.9
        tcr_f = 2.0
    elif model == 'awi_esm_1_1_lr':
        fullname_f = 'AWI-ESM 1.1 LR (2018)'
        mrun_f = 'r1i1p1f1'
        family_f = 'gcm'
        doi_f = '10.1029/2019MS002009, 10.5194/acp-21-5015-2021, 10.1029/2021JC017633, https://pure.mpg.de/rest/items/item_3279802_16/component/file_3316522/content'
        atmos_f = 'ECHAM6.3.04p1 (T63L47 native atmosphere T63 gaussian grid; 192 x 96 longitude/latitude; 47 levels; top level 80 km)'
        surface_f = 'JSBACH 3.20 with dynamic vegetation'
        ocean_f = 'FESOM 1.4 (unstructured grid in the horizontal with 126859 wet nodes; 46 levels; top grid cell 0-5 m)'
        seaice_f = 'FESOM 1.4'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222220100' #provided by Christopher Danek
        addinfo_f = 'Tropospheric and stratospheric ozone is prescribed from the CMIP6 dataset (Checa-Garcia et al., 2018a). GHG concentrations including CO2, CH4, N2O, and chlorofluorocarbons (CFCs) are prescribed after Meinshausen et al. (2017). Methane oxidation and photolysis of water vapour are parameterized for the stratosphere and mesosphere (further information in Sect. 2.1.2 of Schmidt et al., 2013, and references therein)'
        cmip_f = 6
        rgb_f = 'white'
        marker_f = 'v'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 47
        latres_oc_f = 3 #these are pseudo latlons for the unstructured grid containing 126859 wet nodes, confirmed by metadata and array in file
        lonres_oc_f = 42286
        lev_oc_f = 46
        ecs_f = 3.29 #provided by Christopher Danek (source: Semmler et al. 2019, doi:10.1029/2021JC017633)
        tcr_f = 2.11 # "
    elif model == 'bcc_csm1_1':
        fullname_f = 'BCC-CSM1-1'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.5194/gmd-12-1573-2019, 10.1007/s13351-014-3041-7, 10.1002/jgrd.50320, 10.1007/s00382-008-0487-2'
        atmos_f = 'BCC-AGCM2.1, origin: CAM3'
        surface_f = 'BCC-AVIM1.0 + dynamic vegetation + tbgc biophysical module is almost the same as in CLM3, own terrestrial carbon cycle is added'
        ocean_f = 'MOM-L40v1 + obgc'
        seaice_f = 'GFDL-SISv1'
        aerosols_f = 'prescribed'
        chemistry_f = 'none'
        landice_f = 'none'
        obgc_f = 'MOM-L40v1'
        coupler_f = 'NCAR flux coupler version 5'
        complex_f = '2222221120' #Confirmed by Tongwen Wu and Laurent Li, Global carbon budget without spatial distribution, Oceanic carbon cycle based on OCMIP2, https://doi.org/10.5194/gmd-12-1573-2019
        addinfo_f = 'Global carbon budget without spatial distribution, Oceanic carbon cycle based on OCMIP2'
        cmip_f = 5
        rgb_f = '#FF4500'
        marker_f = 'P'
        latres_atm_f = 64
        lonres_atm_f = 128
        lev_atm_f = 26
        latres_oc_f = 232
        lonres_oc_f = 360
        lev_oc_f = 40
        ecs_f = 2.8
        tcr_f = 1.7
    elif model == 'bcc_csm2_mr':
        fullname_f = 'BCC-CSM 2 MR (2017)'
        mrun_f = 'r1i1p1f1'
        family_f = 'esm'
        doi_f = 'https://doi.org/10.5194/gmd-12-1573-2019'
        atmos_f = 'BCC-AGCM3-MR, origin: CAM3'
        surface_f = 'BCC-AVIM2.0 + dynamic vegetation + tbgc, as BCC-AVIM1.0 but with several improvments'
        ocean_f = 'MOM-L40v2 without obgc'
        seaice_f = 'GFDL-SISv2'
        aerosols_f = 'prescribed'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'NCAR flux coupler version 5'
        complex_f = '2222221120' #Confirmed by Tongwen Wu and Laurent Li, Prognostic spatial CO2 in the atmosphere, https://doi.org/10.5194/gmd-12-1573-2019
        addinfo_f = 'Prognostic spatial CO2 in the atmosphere'
        cmip_f = 6
        rgb_f = '#FF4500'
        marker_f = 'v'
        latres_atm_f = 160
        lonres_atm_f = 320
        lev_atm_f = 46
        latres_oc_f = 232
        lonres_oc_f = 360
        lev_oc_f = 40
        ecs_f = 3.0
        tcr_f = 1.7
    elif model == 'canesm2':
        fullname_f = 'CanESM2 2010'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.1029/2010GL046270'
        atmos_f = ' CanAM4 (AGCM15i, T63L35)'
        surface_f = 'CLASS2.7 and CTEM1 (CTEM1 represents the terrestrial carbon cycle)'
        ocean_f = 'CanOM4 (OGCM4.0, 256x192L40)'
        seaice_f = 'CanSIM1 (Cavitating Fluid, T63 Gaussian Grid)'
        aerosols_f = 'interactive tropospheric aerosols and prescribed stratospheric aerosols'
        chemistry_f = 'none'
        obgc_f = 'CMOC1.2'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222222021' #confirmed by Neil Swart
        addinfo_f = 'From e-mail correspondence with Neil Swart: From the CanAM team: For the aerosols in both models there are interactive tropospheric aerosols and prescribed stratospheric aerosols.  The same chemistry is used in CanESM2 and CanESM5, related to the sulphur cycle.  The full chemistry package is not in CanESM5.'
        cmip_f = 5
        rgb_f = 'white'
        marker_f = 'X'
        latres_atm_f = 64
        lonres_atm_f = 128
        lev_atm_f = 35
        latres_oc_f = 192
        lonres_oc_f = 256
        lev_oc_f = 40
        ecs_f = 2.7
        tcr_f = 2.3
    elif model == 'canesm5':
        fullname_f = 'CanESM5 (2019)'
        mrun_f = 'r1i1p2f1'
        family_f = 'esm'
        doi_f = 'doi.org/10.5194/gmd-12-4823-2019'
        atmos_f = 'CanAM5 (T63L49 native atmosphere, T63 Linear Gaussian Grid; 128 x 64 longitude/latitude; 49 levels; top level 1 hPa)'
        surface_f = 'CLASS3.6/CTEM1.2'
        ocean_f = 'NEMO3.4.1 (ORCA1 tripolar grid, 1 deg with refinement to 1/3 deg within 20 degrees of the equator; 361 x 290 longitude/latitude; 45 vertical levels; top grid cell 0-6.19 m)'
        seaice_f = 'LIM2'
        aerosols_f = 'interactive tropospheric aerosols and prescribed stratospheric aerosols. '
        chemistry_f = 'specified oxidants for aerosols'
        obgc_f = 'Canadian Model of Ocean Carbon (CMOC); NPZD ecosystem with OMIP prescribed carbonate chemistry'
        landice_f = 'specified ice sheets'
        coupler_f = 'inhouse'
        complex_f = '2222222121' #confirmed by Neil Swart
        addinfo_f = 'From e-mail correspondence with Neil Swart: vegetation, from the CTEM team: In CanESM5, the fractional coverage of PFTs were specified so vegetation could grow/change vertically in response to changes in climate (i.e. vegetation is interactive). However, since fractional coverage of PFTs were specified vegetation was NOT allowed to compete and move spatially. So competition was off. Typically, however, people use “dynamic vegetation” phrase to describe competition. From the CanAM team: For the aerosols in both models there are interactive tropospheric aerosols and prescribed stratospheric aerosols.  The same chemistry is used in CanESM2 and CanESM5, related to the sulphur cycle.  The full chemistry package is not in CanESM5.'
        cmip_f = 6
        calendar_f = '365_day'
        rgb_f = 'white' #'#ff007f'
        marker_f = 'o'
        latres_atm_f = 64
        lonres_atm_f = 128
        lev_atm_f = 49
        latres_oc_f = 290
        lonres_oc_f = 361
        lev_oc_f = 45
        ecs_f = 5.6
        tcr_f = 2.7
    elif model == 'ccsm4':
        fullname_f = 'CCSM4'
        mrun_f = 'r6i1p1'
        family_f = 'gcm'
        doi_f = '10.1175/2011JCLI4083.1'
        atmos_f = 'CAM4'
        surface_f = 'CLM4'
        ocean_f = 'Parallel Ocean Program version 2'
        seaice_f = 'Community Ice Code version 4'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'CPL7'
        complex_f = '2222221000' #confirmed by Peter Gent
        addinfo_f = ''
        cmip_f = 5
        rgb_f = 'white'
        marker_f = 'P'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 26
        latres_oc_f = 320
        lonres_oc_f = 384
        lev_oc_f = 60
        ecs_f = 2.9
        tcr_f = 1.7
    elif model == 'cmcc_cm': 
        fullname_f = 'CMCC-CM, Euro-Mediterranean Centre on Climate Change coupled climate model'
        mrun_f = 'r1i1p1'
        doi_f = '10.1175/2011JCLI4104.1'
        atmos_f = 'ECHAM5 with a T159 horizontal resolution, Gaussian grid of about 0.75 x 0.75 degrees. This configuration has 31 hybrid sigma-pressure levels in the vertical and top at 10 hPa.'
        surface_f = 'part of ECHAM5'
        ocean_f = 'OPA 8.2 (Madec et al. 1998), in its ORCA2 global configuration. The horizontal resolution is 2 x 2 deg with a meridional refinement near the equator, approaching a minimum 0.5 deg grid spacing. The model has 31 vertical levels, 10 of which lie within the upper 100 m.'
        seaice_f = 'Louvain-La-Neuve (LIM) model'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'Ocean Atmosphere Sea Ice Soil version 3 (OASIS3)'
        complex_f = '2222000000' # # confirmed by Enrico Scoccimarro and Annalisa Cherchie
        addinfo_f = 'model described in the documentation at http://www.cmcc.it/data-models/models'
        family_f = 'gcm'
        cmip_f = 5
        rgb_f = 'cyan'
        marker_f = 'P'
        latres_atm_f = 240
        lonres_atm_f = 480
        lev_atm_f = 31
        latres_oc_f = 149
        lonres_oc_f = 182
        lev_oc_f = 31
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'cmcc_cm2_sr5':
        fullname_f = 'CMCC-CM2-SR5 (2016)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1029/2018MS001369'
        atmos_f = ' CAM5.3 (1deg; 288 x 192 longitude/latitude; 30 levels; top at ~2 hPa)'
        surface_f = 'CLM4.5 (BGC mode)'
        ocean_f = 'NEMO3.6 (ORCA1 tripolar primarly 1 deg lat/lon with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 50 vertical levels; top grid cell 0-1 m)'
        seaice_f = 'CICE4.0'
        aerosols_f = 'MAM3'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'CPL v7'
        complex_f = '2222002000' # # confirmed by Enrico Scoccimarro and Annalisa Cherchie
        addinfo_f = 'In CMCC-CM2, land carbon (C) and nitrogen (N) cycles are activated with the idea to have a better representation of the land surface and vegetation, with a more realistic interaction with the atmosphere. However, the dynamic vegetation module is not active: vegetation can grow, shrink, or die thanks to the interaction with climate and nutrients, but plant functional types, representing vegetation types in each grid cell, are constant. Thus, vegetation types cannot change in response to modified climate conditions.'
        family_f = 'gcm'
        cmip_f = 6
        rgb_f = 'cyan'
        marker_f = 'v'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 30
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 50
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'cmcc_cm2_hr4':
        fullname_f = 'CMCC-CM2-HR4 (2016)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1029/2018MS001369'
        atmos_f = 'CAM4 (1deg; 288 x 192 longitude/latitude; 26 levels; top at ~2 hPa)'
        surface_f = 'CLM4.5 (SP mode)'
        ocean_f = 'NEMO3.6 (ORCA0.25 1/4 deg from the Equator degrading at the poles; 1442 x 1051 longitude/latitude; 50 vertical levels; top grid cell 0-1 m)'
        seaice_f = 'CICE4.0'
        aerosols_f = 'prescribed MACv2-SP'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = ''
        complex_f = '2222001000' # yet has to be confirmed by Enrico Scoccimarro and Annalisa Cherchie
        addinfo_f = 'Very high horizontal ocean resolution'
        family_f = 'gcm'
        cmip_f = 6
        source_f = 'CMCC-CM2-HR4 (2016): \naerosol: prescribed MACv2-SP\natmos: CAM4 (1deg; 288 x 192 longitude/latitude; 26 levels; top at ~2 hPa)\natmosChem: none\nland: CLM4.5 (SP mode)\nlandIce: none\nocean: NEMO3.6 (ORCA0.25 1/4 deg from the Equator degrading at the poles; 1442 x 1051 longitude/latitude; 50 vertical levels; top grid cell 0-1 m)\nocnBgchem: none\nseaIce: CICE4.0'
        rgb_f = 'cyan'
        marker_f = '>'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 26
        latres_oc_f = 1051
        lonres_oc_f = 1442
        lev_oc_f = 50
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'cmcc_esm2':
        fullname_f = 'CMCC-ESM2 (2017)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1029/2018MS001369'
        atmos_f = ' CAM5.3 (1deg; 288 x 192 longitude/latitude; 30 levels; top at ~2 hPa)'
        surface_f = 'CLM4.5 (BGC mode)'
        ocean_f = 'NEMO3.6 (ORCA1 tripolar primarly 1 deg lat/lon with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 50 vertical levels; top grid cell 0-1 m)'
        seaice_f = 'CICE4.0'
        aerosols_f = 'MAM3'
        chemistry_f = 'none'
        obgc_f = 'BFM5.1'
        landice_f = 'none'
        coupler_f = 'CPL v7'
        complex_f = '2222022020' # confirmed by Enrico Scoccimarro and Annalisa Cherchie
        addinfo_f = 'For this model version, it is unclear whether vegetation is dynamic or not.'
        family_f = 'esm'
        cmip_f = 6
        rgb_f = 'cyan'
        marker_f = '<'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 30
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 50
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'cnrm_cm5':
        fullname_f = 'CNRM-CM5 2010'
        mrun_f = 'r1i1p1'
        doi_f = '10.1007/s00382-011-1259-y'
        atmos_f = ' ARPEGE-Climat (V5.2.1, TL127L31), This is a spectral model that operates on a T127 triangular truncation within CNRM-CM5.1 (T63 for CNRM-CM3). All the physics and the calculations of the nonlinear terms require spectral transforms onto a reduced Gaussian grid (Hortal and Simmons 1991) equivalent to a spatial resolution of about 1.4 deg in both longitude and latitude. The dynamical core is based on a two time-level semi Lagrangian numerical integration scheme tagged as cycle 32 of the ARPEGE/IFS system'
        surface_f = ' River Routing: TRIP (v1); Land: SURFEX (v5.1.c), Albedo, vegetation roughness length, vegetation fraction and leaf area index are prescribed by decades given a fixed annual cycle (see page 2094 in 10.1007/s00382-011-1259-y).'
        ocean_f = 'NEMO (nemo3.3.v10.6.6P, ORCA1degL42)'
        seaice_f = 'GELATO (V5.30)'
        aerosols_f = 'prescribed, taken from LMDZ-INCA simulation forced with CMIP5 prescribed emissions; aerosols have an impact on climate. See page 2093 and 2099 in 10.1007/s00382-011-1259-y'
        chemistry_f = 'Page 2093 in 10.1007/s00382-011-1259-y. The ozone-mixing ratio is a prognostic variable with photochemical production and loss rates computed by a 2-D zonal chemistry model (MOBIDIC, Cariolle and Teyssèdre 2007)'
        obgc_f = 'none'
        landice_f = 'Pseudo calving of the Greenland and Antarctic ice sheets, see pages 2094 and 2099 in 10.1007/s00382-011-1259-y'
        coupler_f = 'OASIS 3'
        complex_f = '2222101100' #provided by Aurore Voldoire
        addinfo_f = ''
        family_f = 'gcm'
        cmip_f = 5
        calendar_f = 'gregorian'
        rgb_f = 'red'
        marker_f = 'P'
        latres_atm_f = 128
        lonres_atm_f = 256
        lev_atm_f = 31
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 42
        ecs_f = 3.3
        tcr_f = 2.0
    elif model == 'cnrm_cm6_1':
        fullname_f = 'CNRM-CM6-1 (2017)'
        mrun_f = 'r2i1p1f2'
        doi_f = '10.1029/2019MS001683, 10.1029/2019MS001791'
        atmos_f = 'Arpege 6.3 (T127; Gaussian Reduced with 24572 grid points in total distributed over 128 latitude circles (with 256 grid points per latitude circle between 30 deg N and 30 deg S reducing to 20 grid points per latitude circle at 88.9degN and 88.9degS); 91 levels; top level 78.4 km)'
        surface_f = 'Surfex 8.0c'
        ocean_f = 'Nemo 3.6 (eORCA1, tripolar primarily 1deg; 362 x 294 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'GELATO 6.1'
        aerosols_f = 'prescribed monthly fields computed by TACTIC_v2 scheme, see page 2184'
        chemistry_f = 'OZL_v2' #conflict between file metadata and  reference paper! The reference paper states no chemistry module.
        obgc_f = 'none'
        landice_f = ''
        coupler_f = ''
        complex_f = '2222101100' #provided by Aurore Voldoire
        addinfo_f = '10.1029/2019MS001791, page 4186: The leaf area index (LAI) is not calculated as the result of the carbon balance of the leaves but prescribed from climatological ECOCLIMAP data (Faroux et al., 2013; Masson et al., 2003), involving that only the CO 2 effect on stomatal closure is represented (called the “antitranspiration” effect of CO 2 ). There are no land cover changes in CNRM‐CM6‐1, and the land cover distribution is fixed in time according to the ECOCLIMAP database (Table 2). This database includes climatological observations at high resolution over the 2000s, such as LAI, vegetation roughness length, snow‐free land surface albedo (Carrer et al., 2014), or soil textural properties, from the Harmonized World Soil Database at a 1‐km resolution (HWSD, 2012). More details on the physical processes represented in the ISBA‐CTRIP system can be found in Decharme et al. (2019)' 
        family_f = 'gcm'
        cmip_f = 6
        rgb_f = 'red'
        marker_f = 'v'
        latres_atm_f = 128
        lonres_atm_f = 256
        lev_atm_f = 91
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = 4.8
        tcr_f = 2.1
    elif model =='cnrm_cm6_1_hr':
        fullname_f = 'CNRM-CM6-1-HR (2017)'
        mrun_f = 'r1i1p1f2'
        doi_f = '10.1029/2019MS001683, 10.1029/2019MS001791'
        atmos_f = 'Arpege 6.3 (T359; Gaussian Reduced with 181724 grid points in total distributed over 360 latitude circles (with 720 grid points per latitude circle between 32.2degN and 32.2degS reducing to 18 grid points per latitude circle at 89.6degN and 89.6degS); 91 levels; top level 78.4 km)'
        surface_f = 'Surfex 8.0c'
        ocean_f = 'Nemo 3.6 (eORCA025, tripolar primarily 1/4deg; 1442 x 1050 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'GELATO 6.1'
        aerosols_f = 'prescribed monthly fields computed by TACTIC_v2 scheme, see page 2184'
        chemistry_f = 'OZL_v2' #conflict between file metadata and  reference paper! The reference paper states no chemistry module.
        obgc_f = 'none'
        landice_f = ''
        coupler_f = ''
        complex_f = '2222101100' #provided by Aurore Voldoire
        addinfo_f = ''
        family_f = 'gcm'
        cmip_f = 6
        rgb_f = 'red'
        marker_f = '>'
        latres_atm_f = 360
        lonres_atm_f = 720
        lev_atm_f = 91
        latres_oc_f = 1050
        lonres_oc_f = 1442
        lev_oc_f = 75
        ecs_f = 4.3
        tcr_f = 2.5
    elif model == 'cnrm_esm2_1':
        fullname_f = 'CNRM-ESM2-1 (2017)'
        mrun_f = 'r1i1p1f2'
        doi_f = '10.1029/2019MS001791'
        atmos_f = 'Arpege 6.3 (T127; Gaussian Reduced with 24572 grid points in total distributed over 128 latitude circles (with 256 grid points per latitude circle between 30 deg N and 30 deg S reducing to 20 grid points per latitude circle at 88.9degN and 88.9degS); 91 levels; top level 78.4 km)'
        surface_f = 'Surfex 8.0c'
        ocean_f = 'Nemo 3.6 (eORCA1, tripolar primarily 1deg; 362 x 294 longitude/latitude; 75 levels; top grid cell 0-1 m) '
        seaice_f = 'Gelato 6.1'
        aerosols_f = 'TACTIC_v2'
        chemistry_f = 'REPROBUS-C_v2' #stratospheric chemistry only
        obgc_f = 'Pisces 2.s'
        landice_f = ''
        coupler_f = ''
        complex_f = '2222222220' #provided by Aurore Voldoire under the assumption that interactive stratospheric chemistry only (i.e. tropospheric chemistriy is not interactive) merits a 2
        addinfo_f = 'The included Earth system components are described on pages 4186-4187. See also Table 2. CNRM‐ESM‐2. CNRM‐ESM 2 adds interactive aerosols, stratospheric chemistry, land carbon feedbacks, and ocean biogeochemistry upon CNRM‐CM6‐1 (http://www.umr‐cnrm.fr/cmip6/references). The carbon balance of the leaves controls the vegetation phenology and the LAI as detailed in Gibelin et al. (2006).'
        family_f = 'esm'
        cmip_f = 6
        rgb_f = 'red'
        marker_f = '<'
        latres_atm_f = 360
        lonres_atm_f = 720
        lev_atm_f = 91
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = 4.8
        tcr_f = 1.9
    elif model == 'csiro_mk3_6_0':
        fullname_f = 'CSIRO-Mk3-6-0 2010'
        mrun_f = 'r1i1p1'
        doi_f = 'https://publications.csiro.au/rpr/download?pid=procite:ff94db7e-ad41-40bf-b6be-2ab1ad07805c&dsid=DS1'
        atmos_f = 'AGCM v7.3.8 (T63 spectral, 1.875 degrees EW x approx. 1.875 degrees NS, 18 levels)'
        surface_f = 'inhouse'
        ocean_f = 'GFDL MOM2.2 (1.875 degrees EW x approx. 0.9375 degrees NS, 31 levels) '
        seaice_f = 'inhouse'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = ''
        coupler_f = 'inhouse'
        complex_f = '2222000000'
        addinfo_f = ''
        family_f = 'gcm'
        cmip_f = 5
        rgb_f = 'blue'
        marker_f = 'o'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 18
        latres_oc_f = 189 #retrieved from hfds_Omon_CSIRO-Mk3-6-0_historical_r10i1p1_185001-200512.nc
        lonres_oc_f = 192 #dito
        lev_oc_f = 31
        ecs_f = 4.1
        tcr_f = 1.7
    elif model == 'interim':
        mrun_f = 'r1i1p1'
        family_f = 'reanalysis'
        cmip_f = 1 #this is a fake score in order to be able to work with reanlaysis datasets as if they were GCMs in analysis_hist.py
        complex_f = '1111111111' #this is a fake score in order to be able to work with reanlaysis datasets as if they were GCMs in analysis_hist.py
        rgb_f = 'yellow'
        marker_f = '$INT$'
        latres_atm_f = np.nan
        lonres_atm_f = np.nan
        lev_atm_f = np.nan
        latres_oc_f = np.nan
        lonres_oc_f = np.nan
        lev_oc_f = np.nan
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'ec_earth':
        fullname_f = 'EC-EARTH 2.3 (2011)'
        mrun_f = 'r12i1p1'
        doi_f = '10.1175/2010BAMS2877.1, 10.5194/gmd-2020-446, 10.1007/s00382-011-1228-5'
        atmos_f = 'IFS (cy31R1+modifications, T159L62)'
        surface_f = 'HTessel and LPJ-Guess, see page 21 in 10.5194/gmd-2020-446'
        ocean_f = 'NEMO (version2+modifications, ORCA1-42lev)'
        seaice_f = 'LIM2'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS 3'
        complex_f = '2222001000' #provided by Ralf Döscher and Klaus Wyser
        addinfo_f = 'LPJ-GUESS is a new component in EC-Earth3 (Miller et al., in prep), though it has previously been coupled to EC-Earth v2.3 (Weiss et al. 2012; Alessandri et al. 2017) using a simplified coupling scheme in which updates to leaf area index (LAI) alone were transferred between the submodels.'
        family_f = 'gcm'
        cmip_f = 5
        rgb_f = 'yellow'
        marker_f = 'P'
        latres_atm_f = 160
        lonres_atm_f = 320
        lev_atm_f = 62
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 42
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'ec_earth3':
        fullname_f = 'EC-Earth3 (2019)'
        mrun_f = 'r10i1p1f1'
        doi_f = '10.5194/gmd-2020-446'
        atmos_f = 'IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level 0.01 hPa)'
        surface_f = 'HTESSEL (land surface scheme built in IFS)'
        ocean_f = 'NEMO3.6 (ORCA1 tripolar primarily 1 deg with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'LIM3'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222101000' #provided by Ralf Döscher and Klaus Wyser
        addinfo_f = 'In order to avoid a significant long-term sea-surface height reduction in coupled model runs due to a net precipitation - evaporation (P-E) imbalance in the EC-Earth3 atmosphere of about -0.016 mm/day in the historical period, the coupled model implements a runoff flux corrector, which amplifies river runoff by 7.95% in order to compensate for this effect. The atmospheric component of EC-Earth has been tuned with the goal of achieving a reasonably small radiative imbalance at the top of the atmosphere (TOA) at standard resolution (T255L91 – to which we refer in the following) in present-day atmosphere-standalone (AMIP) runs, using the CERES_EBAF_Ed4.0 dataset as a reference (Loeb et al. 2018).'
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = 'yellow'
        marker_f = 'v'
        latres_atm_f = 256
        lonres_atm_f = 512
        lev_atm_f = 91
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = 4.3
        tcr_f = np.nan
    elif model == 'ec_earth3_veg_lr':
        fullname_f = 'EC-Earth3-Veg-LR (2019)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.5194/gmd-2020-446'
        atmos_f = 'IFS cy36r4 (TL159, linearly reduced Gaussian grid equivalent to 320 x 160 longitude/latitude; 62 levels; top level 5 hPa)'
        surface_f = 'HTESSEL (land surface scheme built in IFS) and LPJ-GUESS v4'
        ocean_f = ' NEMO3.6 (ORCA1 tripolar primarily 1 degree with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'LIM3'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222221000' #provided by Ralf Döscher and Klaus Wyser
        addinfo_f = 'LPJ-GUESS is one of the first vegetation submodels coupled interactively to an atmospheric model, in which the size, age structure, temporal dynamics and spatial heterogeneity of the vegetated landscape are represented and simulated dynamically'
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = 'yellow'
        marker_f = '^'
        latres_atm_f = 160
        lonres_atm_f = 320
        lev_atm_f = 62
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'ec_earth3_veg':
        fullname_f = 'EC-Earth3-Veg (2019)'
        mrun_f = 'r6i1p1f1'
        doi_f = '10.5194/gmd-2020-446'
        atmos_f = 'IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level 0.01 hPa)'
        surface_f = 'HTESSEL (land surface scheme built in IFS) and LPJ-GUESS v4'
        ocean_f = 'NEMO3.6 (ORCA1 tripolar primarily 1 degree with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'LIM3'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222221000' #provided by Ralf Döscher and Klaus Wyser
        addinfo_f = 'LPJ-GUESS is one of the first vegetation submodels coupled interactively to an atmospheric model, in which the size, age structure, temporal dynamics and spatial heterogeneity of the vegetated landscape are represented and simulated dynamically'
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = 'yellow'
        marker_f = '<'
        latres_atm_f = 256
        lonres_atm_f = 512
        lev_atm_f = 91
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = 4.3
        tcr_f = 2.6
    elif model == 'ec_earth3_aerchem':
        fullname_f = 'EC-Earth3-AerChem (2019)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.5194/gmd-2020-446'
        atmos_f = 'IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level 0.01 hPa)'
        surface_f = 'HTESSEL (land surface scheme built in IFS) and LPJ-GUESS v4'
        ocean_f = 'NEMO3.6 (ORCA1 tripolar primarily 1 degree with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'LIM3'
        aerosols_f = 'TM5 (3 x 2 degrees; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)'
        chemistry_f = 'TM5 (3 x 2 degrees; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222102000' #provided by Ralf Döscher and Klaus Wyser
        addinfo_f = 'LPJ-GUESS is one of the first vegetation submodels coupled interactively to an atmospheric model, in which the size, age structure, temporal dynamics and spatial heterogeneity of the vegetated landscape are represented and simulated dynamically'
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = 'yellow'
        marker_f = '>'
        latres_atm_f = 256
        lonres_atm_f = 512
        lev_atm_f = 91
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'ec_earth3_cc':
        fullname_f = 'EC-Earth3-CC (2019)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.5194/gmd-2020-446'
        atmos_f = 'IFS cy36r4 (TL255, linearly reduced Gaussian grid equivalent to 512 x 256 longitude/latitude; 91 levels; top level 0.01 hPa)'
        surface_f = 'HTESSEL (land surface scheme built in IFS) and LPJ-GUESS v4'
        ocean_f = 'NEMO3.6 (ORCA1 tripolar primarily 1 degree with meridional refinement down to 1/3 degree in the tropics; 362 x 292 longitude/latitude; 75 levels; top grid cell 0-1 m)'
        seaice_f = 'LIM3'
        aerosols_f = 'none'
        chemistry_f = 'TM5 (3 x 2 degrees; 120 x 90 longitude/latitude; 34 levels; top level: 0.1 hPa)'
        obgc_f = 'PISCESv2'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222221020' #provided by Ralf Döscher and Klaus Wyser
        addinfo_f = 'LPJ-GUESS is one of the first vegetation submodels coupled interactively to an atmospheric model, in which the size, age structure, temporal dynamics and spatial heterogeneity of the vegetated landscape are represented and simulated dynamically'
        family_f = 'esm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = 'yellow'
        marker_f = 'd'
        latres_atm_f = 256
        lonres_atm_f = 512
        lev_atm_f = 91
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'fgoals_g2':
        fullname_f = 'FGOALS_g2 2011'
        mrun_f = 'r1i1p1'
        family_f = 'gcm'
        doi_f = 'ref. article: 10.1007/s00376-012-2140-6, CLM4: https://opensky.ucar.edu/islandora/object/technotes:493, CLM3: https://opensky.ucar.edu/islandora/object/technotes:393'
        atmos_f = 'GAMIL2, based o a newly introduced dynamical core that was tested in CAM2, see 10.1007/s00376-012-2140-6'
        surface_f = 'CLM3 + dynamic vegetation but without tbgc, which was not yet implemented in CLM3'
        ocean_f = 'LICOM2'
        seaice_f = 'CICE4-LSAG'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'CPL6'
        complex_f = '2222101000' #confirmed by Lijuan Li, ljli@mail.iap.ac.cn
        addinfo_f = 'tbgc not yet present in CLM3'
        cmip_f = 5
        rgb_f = '#800000'
        marker_f = 'P'
        latres_atm_f = 60
        lonres_atm_f = 128
        lev_atm_f = 26
        latres_oc_f = 196
        lonres_oc_f = 360
        lev_oc_f = 30
        ecs_f = 3.4
        tcr_f = 1.4
    elif model == 'fgoals_g3':
        fullname_f = 'FGOALS-g3 (2017)'
        mrun_f = 'r3i1p1f1'
        family_f = 'gcm'
        doi_f = 'ref. article: 10.1029/2019MS002012'
        atmos_f = 'GAMIL3'
        surface_f = 'CAS-LSM, based on CLM4.5'
        ocean_f = 'LICOM3'
        seaice_f = 'CICE4-LSAG'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'CPL7'
        complex_f = '2222111000' #confirmed by Lijuan Li, ljli@mail.iap.ac.cn
        addinfo_f = 'both dynamic vegetation and tbgc present in CLM4.5, includes parametrization of the simple Max Planck Institute Aerosol Climatology model (MACv2‐SP) for anthropogenic aerosol effects'
        cmip_f = 6
        rgb_f = '#800000'
        marker_f = 'v'
        latres_atm_f = 80
        lonres_atm_f = 180
        lev_atm_f = 26
        latres_oc_f = 218
        lonres_oc_f = 360
        lev_oc_f = 30
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'gfdl_cm3':
        fullname_f =' GFDL-CM3 2010'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.1175/2011JCLI3964.1, 10.1175/2011JCLI3955.1'
        atmos_f = 'AM3p9,C48L48'
        surface_f = 'LM3p7_cCM3,C48, carbon balance and vegetation structure simulated by LM3V, see 10.1029/2007GB003176'
        ocean_f = 'MOM4p1_x1_Z50_cCM3,Tripolar360x200L50'
        seaice_f = 'SISp2,Tripolar360x200'
        aerosols_f = 'part of AM3'
        chemistry_f = 'part of AM3'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'unknown'
        complex_f = '2222222200' #confirmed by Huan Guo (NOAA)
        addinfo_f = 'none'
        cmip_f = 5
        calendar_f = '365_day'
        rgb_f = 'magenta'
        marker_f = 'P'
        latres_atm_f = 90
        lonres_atm_f = 144
        lev_atm_f = 48
        latres_oc_f = 200
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = 4.0
        tcr_f = 1.9
    elif model == 'gfdl_esm2g':
        fullname_f = 'GFDL-ESM2G 2010'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.1175/JCLI-D-11-00560.1, 10.1175/JCLI-D-12-00150.1'
        atmos_f = 'AM2 (AM2p14,M45L24)'
        surface_f = 'LM3p7_cESM,M45'
        ocean_f = 'GOLD (ESM2G ocean). However, the source attribute within the .nc files states  TOPAZ (TOPAZ1p2,Tripolar360x210L63)'
        seaice_f = 'SISp2,Tripolar360x210L63'
        aerosols_f = 'prescribed, held constant at 1860 values'
        chemistry_f = 'prescribed, held constant at 1860 values'
        obgc_f = 'GOLD (ESM2G ocean)'
        landice_f = 'simple iceberg calving model'
        coupler_f = 'inhouse'
        complex_f = '2222222221' #still needs to be confirmed by GFDL staff
        addinfo_f = 'none'
        cmip_f = 5
        calendar_f = '365_day'
        rgb_f = 'magenta'
        marker_f = 'X'
        latres_atm_f = 90
        lonres_atm_f = 144
        lev_atm_f = 24
        latres_oc_f = 210
        lonres_oc_f = 360
        lev_oc_f = 63
        ecs_f = 4.0
        tcr_f = 1.9
    elif model == 'gfdl_cm4':
        fullname_f = 'GFDL-CM4 (2018)'
        mrun_f = 'r1i1p1f1'
        family_f = 'esm'
        doi_f = '10.1029/2019MS001829, 10.1029/2019MS002015'
        atmos_f = 'GFDL-AM4.0.1 (Cubed-sphere (c96) - 1 degree nominal horizontal resolution; 360 x 180 longitude/latitude; 33 levels; top level 1 hPa'
        surface_f = 'GFDL-LM4.0.1 (1 degree nominal horizontal resolution; 360 x 180 longitude/latitude; 20 levels; bot level 10m); includes a purely diagnostic land carbon cycle, land:Veg:unnamed (dynamic vegetation, dynamic land use); land:Hydro:unnamed (soil water and ice, multi-layer snow, rivers and lakes)'
        ocean_f = 'GFDL-OM4p25 (GFDL-MOM6, tripolar - nominal 0.25 deg; 1440 x 1080 longitude/latitude; 75 levels; top grid cell 0-2 m)'
        seaice_f = 'GFDL-SIM4p25 (GFDL-SIS2.0, tripolar - nominal 0.25 deg; 1440 x 1080 longitude/latitude; 5 layers; 5 thickness categories)'
        aerosols_f = 'interactive'
        chemistry_f = 'fast chemistry, aerosols are interactive, ozono and other oxdidants are prescribed. Overall, the chemistry in GFDL-CM4 less complex than in GFDL-CM3'
        obgc_f = 'GFDL-BLINGv2, purely diagnostic, not interactive'
        landice_f = 'none'
        coupler_f = 'unknown'
        complex_f = '2222222210' #confirmed by Huan Guo (NOAA)
        addinfo_f = 'GFDL ID: 2019_0065'
        cmip_f = 6
        rgb_f = 'magenta'
        marker_f = 'v'
        latres_atm_f = 180
        lonres_atm_f = 360
        lev_atm_f = 33
        latres_oc_f = 1080
        lonres_oc_f = 1440
        lev_oc_f = 75
        ecs_f = 3.9
        tcr_f = 2.1
    elif model == 'gfdl_esm4':
        fullname_f = 'GFDL-ESM4 (2018)'
        mrun_f = 'r1i1p1f1'
        family_f = 'esm'
        doi_f = '10.1029/2019MS002015'
        atmos_f = 'GFDL-AM4.1 (Cubed-sphere (c96) - 1 degree nominal horizontal resolution; 360 x 180 longitude/latitude; 49 levels; top level 1 Pa)'
        surface_f = 'GFDL-LM4.1'
        ocean_f = 'GFDL-OM4p5 (GFDL-MOM6, tripolar - nominal 0.5 deg; 720 x 576 longitude/latitude; 75 levels; top grid cell 0-2 m)'
        seaice_f = 'GFDL-SIM4p5 (GFDL-SIS2.0, tripolar - nominal 0.5 deg; 720 x 576 longitude/latitude; 5 layers; 5 thickness categories)'
        aerosols_f = 'interactive'
        chemistry_f = ' GFDL-ATMCHEM4.1 (full atmospheric chemistry)'
        obgc_f = 'GFDL-COBALTv2'
        landice_f = 'GFDL-LM4.1'
        coupler_f = 'unknown'
        complex_f = '2222222220' #still needs to be confirmed by GFDL staff
        addinfo_f = 'GFDL ID: 2019_0353'
        cmip_f = 6
        calendar_f = '365_day'
        rgb_f = 'magenta'
        marker_f = '<'
        latres_atm_f = 180
        lonres_atm_f = 360
        lev_atm_f = 49
        latres_oc_f = 576
        lonres_oc_f = 720
        lev_oc_f = 75
        ecs_f = 2.6
        tcr_f = 1.6
    elif model == 'giss_e2_h':
        fullname_f = 'GISS-E2-H-Eh135f9f'        
        mrun_f = 'r6i1p1'
        family_f = 'gcm'
        doi_f = '10.1002/2013MS000266, 10.1002/2013MS000265, 10.1175/JCLI3612.1, 10.1016/j.ocemod.2013.01.008'
        atmos_f = 'ModelE2 AGCM'
        surface_f = 'GISS LSM, including Ent Terrestrial Biosphere Model for dynamic vegetation, all vegetation properties except canopy conductance are prescribed'
        ocean_f = 'Hybrid Coordinate Ocean Model (HYCOM)'
        seaice_f = 'unnamed, part of Hybrid Coordinate Ocean Model (HYCOM)'
        aerosols_f = 'prescribed'
        chemistry_f = 'prescribed'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'unknown'
        complex_f = '2222101100' #provided by Gavin A. Schmidt
        addinfo_f = 'physics_version 1, as indicated by p1, i.e. NINT (non interactive) model version'
        cmip_f = 5
        rgb_f = 'green'
        marker_f = 'X'
        latres_atm_f = 90
        lonres_atm_f = 144
        lev_atm_f = 40
        latres_oc_f = 180
        lonres_oc_f = 360
        lev_oc_f = 33
        ecs_f = 2.3
        tcr_f = 1.7
    elif model == 'giss_e2_r':
        fullname_f = 'GISS-E2-R'
        mrun_f = 'r6i1p1'
        family_f = 'gcm'
        doi_f = '10.1002/2013MS000266, 10.1002/2013MS000265, 10.1175/JCLI3612.1, 10.5194/bg-11-1137-2014'
        atmos_f = 'ModelE2 AGCM'
        surface_f = 'GISS LSM, including Ent Terrestrial Biosphere Model for dynamic vegetation, all vegetation properties except canopy conductance are prescribed'
        ocean_f = 'Russel ocean model'
        seaice_f = 'unnamed, part of Russel ocean model'
        aerosols_f = 'prescribed'
        chemistry_f = 'prescribed'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'unknown'
        complex_f = '2222101100' #provided by Gavin A. Schmidt
        addinfo_f = 'physics_version 1, as indicated by p1, i.e. NINT (non interactive) model version'
        cmip_f = 5
        rgb_f = 'green'
        marker_f = 'P'
        latres_atm_f = 90
        lonres_atm_f = 144
        lev_atm_f = 40
        latres_oc_f = 180
        lonres_oc_f = 288
        lev_oc_f = 32
        ecs_f = 2.1
        tcr_f = 1.5
    elif model == 'giss_e2_1_g':
        fullname_f = 'GISS-E2.1G (2016)'
        mrun_f = 'r1i1p1f1'
        family_f = 'gcm'
        doi_f = '10.1029/2019MS002025, 10.5194/bg-11-1137-2014, 10.1016/j.ocemod.2013.01.008, 10.1029/2019MS002030 for GISS ModelE2.1-G-CC (the carbon cycle version)'
        atmos_f = 'GISS-E2.1 (2.5x2 degree; 144 x 90 longitude/latitude; 40 levels; top level 0.1 hPa)'
        surface_f = 'GISS LSM, including Ent Terrestrial Biosphere Model for dynamic vegetation, all vegetation properties except canopy conductance are prescribed'
        ocean_f = 'GISS Ocean (1.25x1 degree; 288 x 180 longitude/latitude; 32 levels; top grid cell 0-10 m)'
        seaice_f = 'GISS SI'
        aerosols_f = 'prescribed' #There is a conflict between source_id entry stating no aerosol treatment for this run (which is physics version 1 = NINT) and 10.1029/2019MS002025, which states that the NINT version "uses ofﬂine whole‐atmosphere ozone and aerosol ﬁelds from physics‐version 3" (see page 2).
        chemistry_f = 'prescribed'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'unknown'
        complex_f = '2222101100' #provided by Gavin A. Schmidt
        addinfo_f = 'model_id: E200f10aF40oQ40, physics_index 1, in CMIP5, there were three formal versions of the models that varied according to the degree of interactivity in atmospheric composition (physics‐version¼1,2, or 3). In CMIP6, physics‐version 2 has been dropped, physicsversion 1 denoted as NINT (for noninteractive) uses ofﬂine whole‐atmosphere ozone and aerosol ﬁelds from physics‐version 3 the OMA model as described in Bauer et al. (2020), and two new aerosol schemes have been added: TOMAS (denoted by physics‐version 4) (Lee & Adams, 2012) and MATRIX (physics‐version 5) (Bauer et al., 2008), which will be described elsewhere.'
        cmip_f = 6
        rgb_f = 'green'
        marker_f = 'v'
        latres_atm_f = 90
        lonres_atm_f = 144
        lev_atm_f = 40
        latres_oc_f = 180
        lonres_oc_f = 288
        lev_oc_f = 32
        ecs_f = 2.7
        tcr_f = 1.8
    elif model == 'hadgem2_cc':
        fullname_f = 'HadGEM2-CC (2011)'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '0.5194/gmd-4-723-2011,0.5194/gmd-4-1051-2011'
        atmos_f = 'HadGAM2(N96L60)'
        surface_f = 'MOSES2 for land-surface and TRIFFID for dynamic vegetation coupled with the other component models'
        ocean_f = 'HadGOM2 (lat: 1.0-0.3 lon: 1.0 L40)'
        seaice_f = 'inhouse'
        aerosols_f = 'inhouse'
        chemistry_f = 'none'
        obgc_f = 'diat-HadOCC'
        landice_f = 'non-interactive, accumlated ice is not permitted to melt and is therefore permanently removed from the water cycle. The lost freshwater flux returns to the ocean by mean of flux correction.'
        coupler_f = 'inhouse'
        complex_f = '2222222120' # confirmed by by Gill Martin
        addinfo_f = 'It is still rare for dynamic vegetation models to be coupled within climate GCMs. In C4MIP only 2 out of the 11 models were GCMs with dynamic vegetation, and both of those had some form of climate correction term such as ocean heat flux adjustment to enable the vegetation simulation to be sufficiently realistic. HadGEM2 dynamically simulates vegetation without a need for any flux-correction to its climate state.'
        cmip_f = 5
        rgb_f = '#FFA500' #orange
        marker_f = 'X'
        latres_atm_f = 145
        lonres_atm_f = 192
        lev_atm_f = 60
        latres_oc_f = 216
        lonres_oc_f = 360
        lev_oc_f = 40
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'hadgem2_es':
        fullname_f = 'HadGEM2-ES (2009)'
        mrun_f = 'r2i1p1'
        family_f = 'esm'
        doi_f = '0.5194/gmd-4-723-2011,0.5194/gmd-4-1051-2011'
        atmos_f = 'HadGAM2(N96L60)'
        surface_f = 'MOSES2 for land-surface and TRIFFID for dynamic vegetation coupled with the other component models'
        ocean_f = 'HadGOM2 (lat: 1.0-0.3 lon: 1.0 L40)'
        seaice_f = 'inhouse'
        aerosols_f = 'inhouse'
        chemistry_f = 'inhouse'
        obgc_f = 'diat-HadOCC'
        landice_f = 'non-interactive, accumlated ice is not permitted to melt and is therefore permanently removed from the water cycle. The lost freshwater flux returns to the ocean by mean of flux correction.'
        coupler_f = 'inhouse'
        complex_f = '2222222220' #confirmed by Gill Martin
        addinfo_f = 'It is still rare for dynamic vegetation models to be coupled within climate GCMs. In C4MIP only 2 out of the 11 models were GCMs with dynamic vegetation, and both of those had some form of climate correction term such as ocean heat flux adjustment to enable the vegetation simulation to be sufficiently realistic. HadGEM2 dynamically simulates vegetation without a need for any flux-correction to its climate state.'
        cmip_f = 5
        rgb_f = '#FFA500'
        marker_f = 'P'
        latres_atm_f = 145
        lonres_atm_f = 192
        lev_atm_f = 38
        latres_oc_f = 215
        lonres_oc_f = 360
        lev_oc_f = 40
        ecs_f = 4.6
        tcr_f = 2.5
    elif model == 'hadgem3_gc31_mm':
        fullname_f = 'HadGEM3-GC31-MM (2016)'
        mrun_f = 'r1i1p1f3'
        family_f = 'gcm'
        doi_f = '10.5194/gmd-12-4999-2019'
        atmos_f = 'MetUM-HadGEM3-GA7.1 (N216; 432 x 324 longitude/latitude; 85 levels; top level 85 km)'
        surface_f = 'JULES-HadGEM3-GL7.1'
        ocean_f = 'NEMO-HadGEM3-GO6.0 (eORCA025 tripolar primarily 0.25 deg; 1440 x 1205 longitude/latitude; 75 levels; top grid cell 0-1'
        seaice_f = 'CICE-HadGEM3-GSI8 (eORCA025 tripolar primarily 0.25 deg; 1440 x 1205 longitude/latitude)'
        aerosols_f = 'UKCA-GLOMAP-mode'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS-MCT'
        complex_f = '2222002000' #confirmed by Gill Martin
        addinfo_f = ''
        cmip_f = 6
        rgb_f = '#FFA500'
        marker_f = 'v'
        latres_atm_f = 324
        lonres_atm_f = 432
        lev_atm_f = 85
        latres_oc_f = 1205
        lonres_oc_f = 1440
        lev_oc_f = 75
        ecs_f = 5.4
        tcr_f = 2.6
    elif model == 'inm_cm4':
        fullname_f = 'inmcm4 (2009)'
        mrun_f = 'r1i1p1'
        family_f = 'gcm'
        doi_f = '10.1134/S000143381004002X, 10.1175/JCLI-D-12-00831.1'
        atmos_f = 'INM-AM'
        surface_f = 'inhouse'
        ocean_f = 'inhouse'
        seaice_f = 'inhouse'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'inhouse'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222220010' #provided by Evgeny Volodin
        addinfo_f = 'Includes interactive carbon and methane cycles over land, but the representation of ocean biogeochemistry is unclear.'
        source_f = 'inmcm4 (2009)'
        cmip_f = 5
        calendar_f = '365_day'
        rgb_f = '#D3D3D3'
        marker_f = 'P'
        latres_atm_f = 120
        lonres_atm_f = 180
        lev_atm_f = 21
        latres_oc_f = 360
        lonres_oc_f = 360
        lev_oc_f = 40
        ecs_f = 2.1
        tcr_f = 1.3
    elif model == 'inm_cm5':
        fullname_f = 'INM-CM5-0 (2016)'
        mrun_f = 'r2i1p1f1'
        family_f = 'gcm'
        doi_f = '10.1134/S0001433817020128, 10.5194/esd-9-1235-2018, 10.1007/s00382-017-3539-7'
        atmos_f = 'INM-AM5-0'
        surface_f = 'INM-LND1'
        ocean_f = 'INM-OM5'
        seaice_f = 'INM-ICE1'
        aerosols_f = 'INM-AER1'
        chemistry_f = 'none'
        obgc_f = 'inhouse'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222222010' #still has to be confirmed by Evgeny Volodin
        addinfo_f = 'interactive aerosol component'
        source_f = 'INM-CM5-0 (2016): \naerosol: INM-AER1\natmos: INM-AM5-0 (2x1.5; 180 x 120 longitude/latitude; 73 levels; top level sigma = 0.0002)\natmosChem: none\nland: INM-LND1\nlandIce: none\nocean: INM-OM5 (North Pole shifted to 60N, 90E. 0.5x0.25; 720 x 720 longitude/latitude; 40 levels; vertical sigma coordinate)\nocnBgchem: none\nseaIce: INM-ICE1'
        cmip_f = 6
        calendar_f = '365_day'
        rgb_f = '#D3D3D3'
        marker_f = 'X'
        latres_atm_f = 120
        lonres_atm_f = 180
        lev_atm_f = 73
        latres_oc_f = 720
        lonres_oc_f = 720
        lev_oc_f = 40
        ecs_f = 1.9
        tcr_f = np.nan
    elif model == 'ipsl_cm5a_lr':
        fullname_f = 'IPSL-CM5A-LR (2010)'
        mrun_f = 'r5i1p1'
        family_f = 'esm'
        doi_f = '10.1007/s00382-012-1636-1'
        atmos_f = 'LMDZ4 (LMDZ4_v5, 96x95x39)'
        surface_f = 'ORCHIDEE (orchidee_1_9_4_AR5)'
        ocean_f = 'ORCA2 (NEMOV2_3, 2x2L31)'
        seaice_f = 'LIM2 (NEMOV2_3)'
        aerosols_f = 'prescribed from dedicated simulations with INCA (troposphere) and REPROBUS (stratosphere), aerosol effects on climate on time-scale shorter than a month are negleted in a semi-offline approach.'
        chemistry_f = 'prescribed from dedicated simulations with INCA (troposphere) and REPROBUS (stratosphere), chemistry effects on climate on time-scale shorter than a month are negleted in a semi-offline approach.'
        obgc_f = 'PISCES (NEMOV2_3)'
        landice_f = 'none'
        coupler_f = 'OASIS'
        complex_f = '2222221110' # commented by Olivier Boucher but still unclear
        addinfo_f = 'This is the full carbon-cycle configuration of the IPSL-CM5A-LR model. It is however unclear wether CO2 concentrations or emissions were used for this model version (see Fig. 1c, d and pages 2133-34 in 0.1007/s00382-012-1636-1). Most likely, concentrations were used.'
        family_f = 'esm'
        cmip_f = 5
        calendar_f = 'gregorian'
        rgb_f =  'grey'
        marker_f = 'P'
        latres_atm_f = 95
        lonres_atm_f = 96
        lev_atm_f = 39
        latres_oc_f = 149
        lonres_oc_f = 182
        lev_oc_f = 31
        ecs_f = 4.1
        tcr_f = 2.0
    elif model == 'ipsl_cm5a_mr':
        fullname_f = 'IPSL-CM5A-MR (2010)'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.1007/s00382-012-1636-1'
        atmos_f = ' LMDZ4 (LMDZ4_v5, 144x143x39)'
        surface_f = 'ORCHIDEE (orchidee_1_9_4_AR5)'
        ocean_f = 'ORCA2 (NEMOV2_3, 2x2L31)'
        seaice_f = 'LIM2 (NEMOV2_3)'
        aerosols_f = 'prescribed from dedicated simulations with INCA (troposphere) and REPROBUS (stratosphere), aerosol effects on climate on time-scale shorter than a month are negleted in a semi-offline approach.'
        chemistry_f = 'prescribed from dedicated simulations with INCA (troposphere) and REPROBUS (stratosphere), chemistry effects on climate on time-scale shorter than a month are negleted in a semi-offline approach.'
        obgc_f = 'PISCES (NEMOV2_3)'
        landice_f = 'none'
        coupler_f = 'OASIS'
        complex_f = '2222221110' # commented by Olivier Boucher but still unclear
        addinfo_f = 'This is the full carbon-cycle configuration of the IPSL-CM5A-LR model. It is however unclear wether CO2 concentrations or emissions were used for this model version (see Fig. 1c, d and pages 2133-34 in 0.1007/s00382-012-1636-1). Most likely, concentrations were used.'
        cmip_f = 5
        calendar_f = 'gregorian'
        rgb_f =  'grey'
        marker_f = 'X'
        latres_atm_f = 143
        lonres_atm_f = 144
        lev_atm_f = 39
        latres_oc_f = 149
        lonres_oc_f = 182
        lev_oc_f = 31
        ecs_f = np.nan
        tcr_f = 2.0
    elif model == 'ipsl_cm6a_lr':
        fullname_f = 'IPSL-CM6A-LR (2017)'
        mrun_f = 'r17i1p1f1'
        family_f = 'esm'
        doi_f = '10.1029/2019MS002010'
        atmos_f = 'LMDZ (NPv6, N96; 144 x 143 longitude/latitude; 79 levels; top level 40000 m)'
        surface_f = 'ORCHIDEE (v2.0, Water/Carbon/Energy mode)'
        ocean_f = 'NEMO-OPA (eORCA1.3, tripolar primarily 1deg; 362 x 332 longitude/latitude; 75 levels; top grid cell 0-2 m) '
        seaice_f = 'NEMO-LIM3'
        aerosols_f = ''
        chemistry_f = ''
        obgc_f = 'NEMO-PISCES'
        landice_f = 'none'
        coupler_f = 'OASIS3‐MCT'
        complex_f = '2222221121' # commented by Olivier Boucher but still unclear
        addinfo_f = 'internal ice-sheet dynamics are not taken into account by the ice-sheet representation'
        cmip_f = 6
        rgb_f =  'grey'
        marker_f = 'v'
        latres_atm_f = 143
        lonres_atm_f = 144
        lev_atm_f = 79
        latres_oc_f = 332
        lonres_oc_f = 362
        lev_oc_f = 75
        ecs_f = 4.6
        tcr_f = 2.3
    elif model == 'kace_1_0_g':
        fullname_f = 'KACE1.0-G (2018)'
        institution_f = 'National Institute of Meteorological Sciences-Korea Meteorological Administration (NIMS-KMA)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1007/s13143-021-00225-6, 10.1007/s13143-019-00144-7'
        atmos_f = 'MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)'
        surface_f = 'JULES-HadGEM3-GL7.1'
        ocean_f = 'MOM4p1 (tripolar primarily 1deg; 360 x 200 longitude/latitude; 50 levels; top grid cell 0-10 m)'
        seaice_f = 'JULES-HadGEM3-GL7.1'
        aerosols_f = 'UKCA-GLOMAP-mode'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222222000' #yet has to be confirmed
        addinfo_f = 'physics_index: 1, realization_index: 1'
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = '360_day'
        source_f = 'KACE1.0-G (2018): \naerosol: UKCA-GLOMAP-mode\natmos: MetUM-HadGEM3-GA7.1 (N96; 192 x 144 longitude/latitude; 85 levels; top level 85 km)\natmosChem: none\nland: JULES-HadGEM3-GL7.1\nlandIce: none\nocean: MOM4p1 (tripolar primarily 1deg; 360 x 200 longitude/latitude; 50 levels; top grid cell 0-10 m)\nocnBgchem: none\nseaIce: CICE-HadGEM3-GSI8 (tripolar primarily 1deg; 360 x 200 longitude/latitude)'
        rgb_f = 'white'
        marker_f = '<'
        latres_atm_f = 144
        lonres_atm_f = 192
        lev_atm_f = 85
        latres_oc_f = 200
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'kiost_esm':
        fullname_f = 'KIOST-ESM (2018)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1007/s12601-021-00001-7'
        atmos_f = 'GFDL-AM2.0 (cubed sphere (C48); 192 x 96 longitude/latitude; 32 vertical levels; top level 2 hPa)'
        surface_f = 'NCAR-CLM4'
        ocean_f = 'GFDL-MOM5.0 (tripolar - nominal 1.0 deg; 360 x 200 longitude/latitude; 52 levels; top grid cell 0-2 m; NK mixed layer scheme)'
        seaice_f = 'GFDL-SIS'
        aerosols_f = 'none'
        chemistry_f = 'Simple carbon aerosol model (emission type)'
        obgc_f = 'TOPAZ2'
        landice_f = 'none'
        coupler_f = ''
        complex_f = '2222221120' #provided by YoungHo Kim
        addinfo_f = ' based on a low-resolution version of the Geophysical Fluid Dynamics Laboratory Climate Model version 2.5. he main changes made to the base model include using new cumulus convection and ocean mixed layer parameterization schemes, which improve the model fidelity significantly. In addition, the KIOST-ESM adopts dynamic vegetation and new soil respiration schemes in its land model component.'
        family_f = 'esm'
        cmip_f = 6
        rgb_f = 'white'
        marker_f = 's'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 32
        latres_oc_f = 200
        lonres_oc_f = 360
        lev_oc_f = 52
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'mpi_esm_lr':
        fullname_f = 'MPI-ESM-LR 2011'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.1002/jame.20038, 10.1029/2012MS000154'
        atmos_f = 'ECHAM6 (REV: 4603), T63L47'
        surface_f = 'JSBACH (REV: 4603)'
        ocean_f = 'MPIOM (REV: 4603), GR15L40'
        seaice_f = 'unnamed, 4603'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'HAMOCC(REV: 4603)'
        landice_f = 'none'
        coupler_f = 'OASIS3'
        complex_f = '2222220020' #confirmed by Thorsten Mauritsen
        addinfo_f = 'tuning information in 10.1029/2012MS000154, the carbon cycle has been added to the model system. This constitutes the largest conceptual difference between MPI-ESM and its predecessor model ECHAM5/MPIOM [Jungclaus et al, 2006] that has been used for CMIP3. All carbon fluxes from natural vegetation and soils [Schneck et al., 2013], as well as from anthropogenic land use and land use change [Pongratz et al., 2009] are simulated consistently.'
        cmip_f = 5
        rgb_f = '#00FF00'
        marker_f = 'P'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 47
        latres_oc_f = 220
        lonres_oc_f = 256
        lev_oc_f = 40
        ecs_f = 3.6
        tcr_f = 2.0
    elif model == 'mpi_esm_mr':
        fullname_f = 'MPI-ESM-MR 2011'
        mrun_f = 'r1i1p1'
        family_f = 'esm'
        doi_f = '10.1002/jame.20038, 10.1029/2012MS000154'
        atmos_f = 'ECHAM6 (REV: 4936), T63L47'
        surface_f = 'JSBACH (REV: 4936)'
        ocean_f = ' MPIOM (REV: 4936), GR15L40'
        seaice_f = 'unnamed, 4936'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'HAMOCC(REV: 4936)'
        landice_f = 'none'
        coupler_f = 'OASIS3'
        complex_f = '2222220020' #confirmed by Thorsten Mauritsen
        addinfo_f = 'tuning information in 10.1029/2012MS000154, the carbon cycle has been added to the model system. This constitutes the largest conceptual difference between MPI-ESM and its predecessor model ECHAM5/MPIOM [Jungclaus et al, 2006] that has been used for CMIP3. All carbon fluxes from natural vegetation and soils [Schneck et al., 2013], as well as from anthropogenic land use and land use change [Pongratz et al., 2009] are simulated consistently.'
        cmip_f = 5
        calendar_f = 'gregorian'
        rgb_f = '#00FF00'
        marker_f = 'X'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 95
        latres_oc_f = 404 #from array in file
        lonres_oc_f = 802 #from array in file
        lev_oc_f = 40 #from array in file
        ecs_f = 3.5
        tcr_f = 2.0
    elif model == 'mpi_esm_1_2_lr':
        fullname_f = 'MPI-ESM1.2-LR (2017)'
        mrun_f = 'r10i1p1f1'
        family_f = 'esm'
        doi_f = '10.1029/2018MS001400'
        atmos_f = 'ECHAM6.3 (spectral T63; 192 x 96 longitude/latitude; 47 levels; top level 0.01 hPa)'
        surface_f = 'JSBACH3.20'
        ocean_f = 'MPIOM1.63 (bipolar GR1.5, approximately 1.5deg; 256 x 220 longitude/latitude; 40 levels; top grid cell 0-12 m)'
        seaice_f = 'unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)'
        aerosols_f = 'none, prescribed MACv2-SP'
        chemistry_f = 'none'
        obgc_f = 'HAMOCC6'
        landice_f = 'none/prescribed'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222221020' #confirmed by Thorsten Mauritsen
        addinfo_f = 'Among other aspects, coding errors were corrected in this version. The vegetation distribution is dynamically computed.'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = '#00FF00'
        marker_f = 'v'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 47
        latres_oc_f = 220 #from array in file
        lonres_oc_f = 256 #from array in file
        lev_oc_f = 40 #from array in file
        ecs_f = 3.0
        tcr_f = 1.8
    elif model == 'mpi_esm_1_2_ham':
        fullname_f = 'MPI-ESM1.2-HAM (2017)'
        mrun_f = 'r1i1p1f1'
        family_f = 'esm'
        doi_f = '10.5194/gmd-12-1643-2019, 10.5194/gmd-2018-307'
        atmos_f = 'ECHAM6.3 (spectral T63; 192 x 96 longitude/latitude; 47 levels; top level 0.01 hPa)'
        surface_f = 'JSBACH3.20'
        ocean_f = 'MPIOM1.63 (bipolar GR1.5, approximately 1.5deg; 256 x 220 longitude/latitude; 40 levels; top grid cell 0-12m)'
        seaice_f = 'unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)'
        aerosols_f = 'HAM2.3'
        chemistry_f = 'sulfur chemistry (unnamed)' # the fully atmospheric chemistry component called MOZ is missing here
        obgc_f = 'HAMOCC6'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222222120' #confirmed by Ina Tegen
        addinfo_f = 'https://cera-www.dkrz.de/WDCC/ui/cerasearch/cmip6?input=CMIP6.AerChemMIP.HAMMOZ-Consortium.MPI-ESM-1-2-HAM'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = '#00FF00'
        marker_f = '^'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 47
        latres_oc_f = 220 #from metadata in file
        lonres_oc_f = 256 #from metadata in file
        lev_oc_f = 40 #from metadata in file
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'mpi_esm_1_2_hr':
        fullname_f = 'MPI-ESM1.2-HR (2017)'
        mrun_f = 'r8i1p1f1'
        doi_f = '10.1029/2018MS001400, 10.5194/gmd-12-3241-2019'
        atmos_f = 'ECHAM6.3 (spectral T127; 384 x 192 longitude/latitude; 95 levels; top level 0.01 hPa)'
        surface_f = 'JSBACH3.20'
        ocean_f = 'MPIOM1.63 (tripolar TP04, approximately 0.4deg; 802 x 404 longitude/latitude; 40 levels; top grid cell 0-12m)'
        seaice_f = 'unnamed (thermodynamic (Semtner zero-layer) dynamic (Hibler 79) sea ice model)'
        aerosols_f = 'none, prescribed MACv2-SP'
        chemistry_f = 'none'
        obgc_f = 'HAMOCC6'
        landice_f = 'none/prescribed'
        coupler_f = 'OASIS3-MCT'
        complex_f = '2222221020' #confirmed by Thorsten Mauritsen
        addinfo_f = 'In this model version the land carbon cycle was not run to equilibrium and the vegetation distribution is prescribed by a map.'
        family_f = 'esm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = '#00FF00'
        marker_f = '>'
        latres_atm_f = 192
        lonres_atm_f = 384
        lev_atm_f = 95
        latres_oc_f = 404 #from metadata in file
        lonres_oc_f = 802 #from metadata in file
        lev_oc_f = 40 #from metadata in file
        ecs_f = 3.0
        tcr_f = 1.7
    elif model == 'miroc5':
        fullname_f = 'MIROC5 2010'
        mrun_f = 'r1i1p1'
        doi_f = '10.1175/2010JCLI3679.1'
        atmos_f = 'MIROC-AGCM5 (T85L40)'
        surface_f = 'MATSIRO (MATSIRO, L6)'
        ocean_f = 'COCO (COCO4.5, 256x224 L50)'
        seaice_f = 'COCO (COCO4.5)'
        aerosols_f = 'SPRINTARS (SPRINTARS 5.00, T85L40)' #interactive in the troposphere only, stratospheric chemistry is prescribed
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222102000' #provided by Hiroaki Tatebe
        addinfo_f = 'SPRINTARS is interactive in the troposphere only, stratospheric chemistry is prescribed. The boundary conditions for the land module consist of the fractions of three tiles (potential vegetation, cropland, and lake), the distribution of potential vegetation, and the leaf area index (LAI).'
        family_f = 'gcm'
        cmip_f = 5
        rgb_f = '#008080'
        marker_f = 'P'
        latres_atm_f = 128
        lonres_atm_f = 256
        lev_atm_f = 40
        latres_oc_f = 224 #from metadata in file
        lonres_oc_f = 256 #from metadata in file
        lev_oc_f = 50 #from metadata in file
        ecs_f = 2.7
        tcr_f = 1.4
    elif model == 'miroc_esm':
        fullname_f = 'MIROC-ESM 2010'
        mrun_f = 'r1i1p1'
        doi_f = '10.5194/gmd-4-845-2011'
        atmos_f = 'MIROC-AGCM (MIROC-AGCM 2010, T42L80)'
        surface_f = 'MATSIRO (MATSIRO, L6)'
        ocean_f = ' COCO (COCO3.4, 256x192 L44)'
        seaice_f = ' COCO (COCO3.4)'
        aerosols_f = ' SPRINTARS (SPRINTARS 5.00, T42L80)'
        chemistry_f = 'CHASER'
        obgc_f = 'NPZD'
        lbgc_f = 'SEIB-DGVM (SEIB-DGVM, T42)'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222222020' #provided by Hiroaki Tatebe
        addinfo_f = 'For an overview for the physical variables and chemical species interacting in a full ESM, Table 1 in 10.5194/gmd-4-845-2011 is very instructive.'
        family_f = 'esm'
        cmip_f = 5
        rgb_f = '#008080'
        marker_f = 'X'
        latres_atm_f = 64
        lonres_atm_f = 128
        lev_atm_f = 80
        latres_oc_f = 192 #from metadata in file
        lonres_oc_f = 256 #from metadata in file
        lev_oc_f = 44 #from metadata in file
        ecs_f = 4.7
        tcr_f = 2.2
    elif model == 'miroc6':
        fullname_f = 'MIROC6 (2017)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.5194/gmd-12-2727-2019'
        atmos_f = 'CCSR AGCM (T85; 256 x 128 longitude/latitude; 81 levels; top level 0.004 hPa)'
        surface_f = 'MATSIRO6.0'
        ocean_f = 'COCO4.9 (tripolar primarily 1deg; 360 x 256 longitude/latitude; 63 levels; top grid cell 0-2 m)'
        seaice_f = 'COCO4.9'
        aerosols_f = 'SPRINTARS6.0'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222102000' #provided by Hiroaki Tatebe
        addinfo_f = 'SPRINTARS is interactive in the troposphere only, stratospheric chemistry is prescribed. Vegetation and soil properties are prescribed.'
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = '#008080'
        marker_f = 'v'
        latres_atm_f = 128
        lonres_atm_f = 256
        lev_atm_f = 81
        latres_oc_f = 256 #from metadata in file
        lonres_oc_f = 360 #from metadata in file
        lev_oc_f = 63 #from metadata in file
        ecs_f = 2.6
        tcr_f = 1.6
    elif model == 'miroc_es2l':
        fullname_f = 'MIROC-ES2L (2018)'
        mrun_f = 'r1i1p1f2'
        doi_f = '10.5194/gmd-13-2197-2020'
        atmos_f = ' CCSR AGCM (T42; 128 x 64 longitude/latitude; 40 levels; top level 3 hPa)'
        surface_f = 'MATSIRO6.0+VISIT-e ver.1.0'
        ocean_f = 'COCO4.9 (tripolar primarily 1deg; 360 x 256 longitude/latitude; 63 levels; top grid cell 0-2 m)'
        seaice_f = 'COCO4.9'
        aerosols_f = 'SPRINTARS6.0'
        chemistry_f = 'none'
        obgc_f = 'OECO ver.2.0; NPZD-type with C/N/P/Fe/O cycles'
        landice_f = 'none'
        coupler_f = 'inhouse'
        complex_f = '2222022020' #provided by Hiroaki Tatebe
        addinfo_f = ''
        family_f = 'esm'
        cmip_f = 6
        rgb_f = '#008080' ##ADD8E6
        marker_f = '<'
        latres_atm_f = 64
        lonres_atm_f = 128
        lev_atm_f = 40
        latres_oc_f = 256 #from metadata in file
        lonres_oc_f = 360 #from metadata in file
        lev_oc_f = 63 #from metadata in file
        ecs_f = 2.7
        tcr_f = 1.6
    elif model == 'jra55':
        mrun_f = 'r1i1p1'
        family_f = 'reanalysis'
        cmip_f = 1 #this is a fake score in order to be able to work with reanlaysis datasets as if they were GCMs in analysis_hist.py
        complex_f = '1111111111' #this is a fake score in order to be able to work with reanlaysis datasets as if they were GCMs in analysis_hist.py
        rgb_f = '#B5651D'
        marker_f = '$JRA$'
        latres_atm_f = np.nan
        lonres_atm_f = np.nan
        lev_atm_f = np.nan
        latres_oc_f = np.nan
        lonres_oc_f = np.nan
        lev_oc_f = np.nan
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'mri_esm1':
        fullname_f = 'MRI-ESM1 2011'
        mrun_f = 'r1i1p1'
        doi_f = '10.11483/mritechrepo.64'
        atmos_f = 'GSMUV (gsmuv-110120oc, TL159L48)'
        surface_f = 'HAL (HAL_cmip5_v0.31_04)'
        ocean_f = 'COCO4.9 (tripolar primarily 1deg; 360 x 256 longitude/latitude; 63 levels; top grid cell 0-2 m)'
        seaice_f = 'MRI.COM3'
        aerosols_f = 'MASINGAR-mk2 (masingar_mk2-20110111_1121, TL95L48)'
        chemistry_f = 'MRI-CCM2 (ccm2-101129, T42L48)'
        obgc_f = 'MRI.COM3'
        landice_f = 'SMIST'
        coupler_f = 'Scup'
        complex_f = '2222122220' #provided by Seiji Yukimoto
        addinfo_f = 'SMIST is a simple ice sheet and iceberg calving model that does not include 3D dynamic and thermodynamic ice sheet dynamics. These were planned to be included in the more complex SICOPOLIS model'
        family_f = 'esm'
        cmip_f = 5
        rgb_f = '#B5651D'
        marker_f = 'P'
        latres_atm_f = 160
        lonres_atm_f = 320
        lev_atm_f = 48
        latres_oc_f = 368 #from Yukimoto et al. 2011
        lonres_oc_f = 364
        lev_oc_f = 51
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'mri_esm2_0':
        fullname_f = 'MRI-ESM2.0 (2017)'
        mrun_f = 'r4i1p1f1'
        doi_f = '10.2151/jmsj.2019-051'
        atmos_f = 'MRI-AGCM3.5 (TL159; 320 x 160 longitude/latitude; 80 levels; top level 0.01 hPa)'
        surface_f = ' HAL 1.0'
        ocean_f = 'MRI.COM4.4 (tripolar primarily 0.5 deg latitude/1 deg longitude with meridional refinement down to 0.3 deg within 10 degrees north and south of the equator; 360 x 364 longitude/latitude; 61 levels; top grid cell 0-2 m)'
        seaice_f = 'MRI.COM4.4'
        aerosols_f = 'MASINGAR mk2r4 (TL95; 192 x 96 longitude/latitude; 80 levels; top level 0.01 hPa)'
        chemistry_f = 'MRI-CCM2.1 (T42; 128 x 64 longitude/latitude; 80 levels; top level 0.01 hPa)'
        obgc_f = 'MRI.COM4.4'
        landice_f = 'none'
        coupler_f = 'Scup'
        complex_f = '2222112210' #122220 for r1i2p1f1, provided by Seiji Yukimoto
        addinfo_f = ''
        family_f = 'esm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = '#B5651D'
        marker_f = 'v'
        latres_atm_f = 160
        lonres_atm_f = 320
        lev_atm_f = 80
        latres_oc_f = 364 #from metadata in file
        lonres_oc_f = 360
        lev_oc_f = 61
        ecs_f = 3.2
        tcr_f = 1.6
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'noresm1_m':
        fullname_f = 'NorESM1-M 2011'
        mrun_f = 'r1i1p1'
        doi_f = '10.5194/gmd-6-687-2013'
        atmos_f = 'CAM-Oslo (CAM4-Oslo-noresm-ver1_cmip5-r112, f19L26)'
        surface_f = 'CLM (CLM4-noresm-ver1_cmip5-r112)'
        ocean_f = 'MICOM (MICOM-noresm-ver1_cmip5-r112, gx1v6L53)'
        seaice_f = 'CICE (CICE4-noresm-ver1_cmip5-r112)'
        aerosols_f = 'CAM-Oslo (CAM4-Oslo-noresm-ver1_cmip5-r112, f19L26)'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'CPL7'
        complex_f = '2222122000' #confirmed by Øyvind Seland
        addinfo_f = 'based on the Community Climate System Model version 4 (CCSM4); in the NorESM experiments discussed in this study, the carbon–nitrogen (CN) cycle option of CLM4 is enabled (Thornton et al., 2007; Gent et al., 2011). Within the land component the carbon and nitrogen are prognostic variables, while carbon and nitrogen fluxes are diagnostically determined and do not influence other model components.'
        family_f = 'gcm'
        cmip_f = 5
        rgb_f = '#FFB6C1'
        marker_f = 'P'
        latres_atm_f = 96
        lonres_atm_f = 144
        lev_atm_f = 26
        latres_oc_f = 320
        lonres_oc_f = 384
        lev_oc_f = 53 #70 in oceanfile
        ecs_f = 2.8
        tcr_f = 1.4
        ecs_f = 2.8
        tcr_f = 1.4
    elif model == 'noresm2_lm':
        fullname_f = 'NorESM2-LM (2017)'
        mrun_f = 'r2i1p1f1'
        doi_f = '10.5194/gmd-6-687-2013'
        atmos_f = 'CAM-OSLO (2 degree resolution; 144 x 96; 32 levels; top level 3 mb), based on CAM6'
        surface_f = 'CLM5'
        ocean_f = 'BLOM, based on MICOM (1 degree resolution; 360 x 384; 70 levels; top grid cell minimum 0-2.5 m [native model uses hybrid density and generic upper-layer coordinate interpolated to z-level for contributed data])'
        seaice_f = 'CICE5'
        aerosols_f = 'OsloAero6'
        chemistry_f = 'OsloChemSimp'
        obgc_f = 'iHAMOCC'
        landice_f = 'none' #WARNING: while 10.5194/gmd-2019-378 states CISM is not activated, it is indicated in the source_id attribute of the models' nc files. These information are in conflict.
        coupler_f = 'CPL7'
        complex_f = '2222122120' #confirmed by Øyvind Seland
        addinfo_f = ''
        family_f = 'esm'
        cmip_f = 6
        calendar_f = '365_day'
        rgb_f = '#FFB6C1'
        marker_f = 'v'
        latres_atm_f = 96
        lonres_atm_f = 144
        lev_atm_f = 32
        latres_oc_f = 360 #from array in file
        lonres_oc_f = 384
        lev_oc_f = 53 #or 70?
        ecs_f = 2.5
        tcr_f = 1.5
        co2_f = 'concentrations' #concentrations or emissions
    elif model == 'noresm2_mm':
        fullname_f = 'NorESM2-MM (2017)'
        mrun_f = 'r3i1p1f1'
        doi_f = '10.5194/gmd-6-687-2013'
        atmos_f = 'CAM-OSLO (1 degree resolution; 288 x 192; 32 levels; top level 3 mb), based on CAM6'
        surface_f = 'CLM5'
        ocean_f = 'BLOM, based on MICOM (1 degree resolution; 360 x 384; 70 levels; top grid cell minimum 0-2.5 m [native model uses hybrid density and generic upper-layer coordinate interpolated to z-level for contributed data])'
        seaice_f = 'CICE5'
        aerosols_f = 'OsloAero6'
        chemistry_f = 'OsloChemSimp'
        obgc_f = 'iHAMOCC'
        landice_f = 'none' #WARNING: while 10.5194/gmd-2019-378 states CISM is not activated, it is indicated in the source_id attribute of the models' nc files. These information are in conflict.
        coupler_f = 'CPL7'
        complex_f = '2222122120' #confirmed by Øyvind Seland
        addinfo_f = 'based on CESM2.1, differs from noresm2_lm only in terms of the AGCMs horizontal resolution'
        family_f = 'esm'
        cmip_f = 6
        calendar_f = '365_day'
        rgb_f = '#FFB6C1'
        marker_f = '<'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 32
        latres_oc_f = 360
        lonres_oc_f = 384
        lev_oc_f = 53 # or 70?
        ecs_f = np.nan
        tcr_f = np.nan
        co2_f = 'concentrations'
    elif model == 'nesm3': #v3
        fullname_f = 'NESM v3 (2016)'
        mrun_f = 'r5i1p1f1'
        doi_f = '10.5194/gmd-11-2975-2018'
        atmos_f = 'ECHAM v6.3 (T63; 192 x 96)'
        surface_f = 'JSBACH v3.1'
        ocean_f = 'NEMO v3.4 (NEMO v3.4, tripolar primarily 1deg; 384 x 362 longitude/latitude; 46 levels; top grid cell 0-6 m)'
        seaice_f = 'CICE4.1'
        aerosols_f = 'none'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'OASIS3-MCT3.0'
        complex_f = '2222221000' #provided by Dr. Jian Cao
        addinfo_f = ''
        family_f = 'gcm'
        cmip_f = 6
        calendar_f = 'gregorian'
        rgb_f = 'white'
        marker_f = '>'
        latres_atm_f = 96
        lonres_atm_f = 192
        lev_atm_f = 47
        latres_oc_f = 292
        lonres_oc_f = 362
        lev_oc_f = 46
        ecs_f = 4.7
        tcr_f = 2.7
    elif model == 'sam0_unicon': #v2017
        fullname_f = 'SAM0-UNICON (2017)'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1175/JCLI-D-18-0796.1'
        atmos_f = 'CAM5.3 with UNICON (1deg; 288 x 192 longitude/latitude; 30 levels; top level ~2 hPa)'
        surface_f = 'CLM4.0'
        ocean_f = 'POP2 (Displaced Pole; 320 x 384 longitude/latitude; 60 levels; top grid cell 0-10 m)'
        seaice_f = 'CICE4.0'
        aerosols_f = 'MAM3'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = 'not specified in reference article or source_id attribute but should be CPL'
        complex_f = '2222222000' #treatment of tbgc is unclear from the reference article, but normally taken into account by CLM4, needs to be confirmed by the corresponding model development team yet
        addinfo_f = 'based on CESM1. Mainly, the parametrization schemes of CAM5.3 have been modified.'
        family_f = 'esm'
        cmip_f = 6
        rgb_f = 'white'
        marker_f = '^'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 30
        latres_oc_f = 384 #from metadata in file
        lonres_oc_f = 320
        lev_oc_f = 60
        ecs_f = 3.7
        tcr_f = 2.3
    elif model == 'taiesm1':
        fullname_f = 'TaiESM 1.0 (2018), based on CAM5.3'
        mrun_f = 'r1i1p1f1'
        doi_f = '10.5194/gmd-13-3887-2020'
        atmos_f = 'TaiAM1 (0.9x1.25 degree; 288 x 192 longitude/latitude; 30 levels; top level ~2 hPa)'
        surface_f = 'CLM4.0 (same grid as atmos)'
        ocean_f = 'POP2 (320x384 longitude/latitude; 60 levels; top grid cell 0-10 m)'
        seaice_f = 'CICE4'
        aerosols_f = 'SNAP (same grid as atmos)'
        chemistry_f = 'none'
        obgc_f = 'none'
        landice_f = 'none'
        coupler_f = ''
        complex_f = '2222222000' #confirmed by Wei-Liang Lee: "Most numbers are correct except the "vegetation" that I am not quite sure about. We did not turn on dynamic vegetation in our land model (CLM4). The fraction of land use is given by the input file but not simulated. However, the biomass can evolve because we turned on the carbon-nitrogen process. Therefore, maybe "vegetation" should be 1 (but it depends on how you define interactive for vegetation)."
        addinfo_f = 'based on CESM1.2.2, incorporating several innovative physical and chemical parameterizations'
        family_f = 'esm'
        cmip_f = 6
        rgb_f = 'white'
        marker_f = 'd'
        latres_atm_f = 192
        lonres_atm_f = 288
        lev_atm_f = 30
        latres_oc_f = 320
        lonres_oc_f = 384
        lev_oc_f = 60
        ecs_f = np.nan
        tcr_f = np.nan
    elif model == 'iitm_esm':
        fullname_f = 'IITM-ESM (2015)' #full name of the coupled model as specified in the source_id attribute of the netCDF files
        mrun_f = 'r1i1p1f1'
        doi_f = '10.1175/BAMS-D-13-00276.2'
        atmos_f = 'IITM-GFSv1 (T62L64, Linearly Reduced Gaussian Grid; 192 x 94 longitude/latitude; 64 levels; top level 0.2 mb)'
        surface_f = 'NOAH LSMv2.7.1'
        ocean_f = 'MOM4p1 (tripolar, primarily 1deg; 360 x 200 longitude/latitude; 50 levels; top grid cell 0-10 m)'
        seaice_f = 'SISv1.0'
        aerosols_f = 'prescribed MAC-v2'
        chemistry_f = 'none'
        obgc_f = 'TOPAZv2.0'
        landice_f = 'none'
        coupler_f = 'no info in refernce article'
        complex_f = '2222101020' #provided by Panickal Swapna
        addinfo_f = 'physics_index: 1'
        family_f = 'gcm'
        cmip_f = 6
        rgb_f = 'white'
        marker_f = 'H'
        latres_atm_f = 192
        lonres_atm_f = 94
        lev_atm_f = 64
        latres_oc_f = 200
        lonres_oc_f = 360
        lev_oc_f = 50
        ecs_f = np.nan
        tcr_f = 1.7
    else:
        raise Exception('Error: check entry for <model> !!')
    
    return(mrun_f,complex_f,family_f,cmip_f,rgb_f,marker_f,latres_atm_f,lonres_atm_f,lev_atm_f,latres_oc_f,lonres_oc_f,lev_oc_f,ecs_f,tcr_f)
